/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF';
import { Canvas, useFrame} from "react-three-fiber";

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Tesla_CyberTruck_v2_Condensed.glb')

  const frontTireRef = useRef()
  const frontRimRef = useRef()
  const rearTireRef = useRef()
  const rearRimRef = useRef()
  const speed = props.speed
  useFrame(()=> {
    frontTireRef.current.rotation.z -= speed
    frontRimRef.current.rotation.z -= speed
    rearTireRef.current.rotation.z -= speed
    rearRimRef.current.rotation.z -= speed
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Hood.geometry}
        material={nodes.Hood.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        metalness={1}
        castShadow
      />
      <mesh
        geometry={nodes.Headlight.geometry}
        material={materials['Light.004']}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
      />
      <mesh
        geometry={nodes.TailGate.geometry}
        material={nodes.Front_Door.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <group position={[0, 0.95, 0]} scale={[5.89, 1.9, 2.03]}>
        <mesh geometry={nodes.Cube059.geometry} material={materials['Material.007']} castShadow/>
        <mesh geometry={nodes.Cube059_1.geometry} material={nodes.Cube059_1.material} castShadow/>
      </group>
      <mesh
        geometry={nodes.Rear_Cover001.geometry}
        material={nodes.Rear_Cover001.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Roof001.geometry}
        material={nodes.Front_Door.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Front_Glass.geometry}
        material={nodes.Front_Glass.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Side_window1.geometry}
        material={nodes.Side_window1.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
      />
      <mesh
        geometry={nodes.Sidewindow2.geometry}
        material={nodes.Sidewindow2.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Side_WIndow3.geometry}
        material={nodes.Side_WIndow3.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Front_Door.geometry}
        material={nodes.Front_Door.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Rear_Door.geometry}
        material={nodes.Rear_Door.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Rear_Handle.geometry}
        material={nodes.Rear_Handle.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Door_Handle.geometry}
        material={nodes.Door_Handle.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.A_Pillar.geometry}
        material={nodes.A_Pillar.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Front_Wheel_Well.geometry}
        material={nodes.Front_Wheel_Well.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Rear_Fender.geometry}
        material={nodes.Rear_Fender.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Underbody.geometry}
        material={nodes.Underbody.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <group position={[0, 0.95, 0]} scale={[5.89, 1.9, 2.03]}>
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh
        geometry={nodes.Front_Bumber.geometry}
        material={nodes.Front_Bumber.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Rear_Bumper.geometry}
        material={nodes.Rear_Bumper.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Front_BOdy.geometry}
        material={nodes.Front_BOdy.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Front_Fender.geometry}
        material={nodes.Front_Fender.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Rear_Wheel_Well.geometry}
        material={nodes.Rear_Wheel_Well.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />
      <mesh
        geometry={nodes.Front_BLackout.geometry}
        material={nodes.Front_BLackout.material}
        position={[0, 0.95, 0]}
        scale={[5.89, 1.9, 2.03]}
        castShadow
      />

      <mesh geometry={nodes.Tire.geometry} material={nodes.Tire.material} position={[2.07, 0.46, 0]} ref = {frontTireRef} castShadow/>
      <mesh geometry={nodes.Rim.geometry} material={nodes.Rim.material} position={[2.07, 0.47, 0]} ref = {frontRimRef} castShadow/>
      
      <mesh geometry={nodes.Tire001.geometry} material={nodes.Tire001.material} position={[-1.83, 0.46, 0]} ref = {rearTireRef} castShadow/>
      <mesh geometry={nodes.Rim001.geometry} material={nodes.Rim001.material} position={[-1.83, 0.47, 0]} ref = {rearRimRef} castShadow/>
    </group>
  )
}

useGLTF.preload('/Tesla_CyberTruck_v2_Condensed.glb')
